#+BLOG: Blog
#+POSTID: 274
#+DATE: [2013-07-24 Wed 13:19]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Life, 日志, English
#+TAGS:Life, 日志, English
#+DESCRIPTION:
#+TITLE: TED2013 Meg Jay: 20岁，不可挥霍的光阴

* Leonard Bernstein said that to achieve great things, you need a plan and not quite enough time.

Isn't that true? So, what you think happen when you pat a
20something on the head and you say, " You have 10 extra years
to start your life." 

Nothing happen. You have robbed that person of his urgency and
ambition, and absolutely nothing happens. 

And then every day, smart, interesting twentysomethings, like you
and like your sons and daughters, come into my office and say
things like this: "I know my boyfriend no good for me but this
relationship doesn't count, I'm just killing time." Or they say,
" Everybody say as long as I started on a career by the time I'm
30, I'll be fine." But then it starts to sound like this: "My 20s
almost over, and I have nothing to show for myself. I had a
better resume the day after I graduated from my college." And
then it starts to sound like this: "Dating at my 20s was like
musical chairs, Everybody was running around and having fun, but
then sometime around 30 it was like the music turned off and
everybody started to siting down, I didn't want to be the only
one left standing up, so sometimes I think I married with my
husband, because he was the closest chair to me at 30." 

Do not do that. 


20somethings are like airplanes just leaving LAX, bound for
somewhere west. Right after takeoff, a slight changing cause is
a difference between landing in Alaska or Fiji.   

*Thirty is not a new 20, so claim your adulthood, get some
identity capital, use your weak ties, pick your family.*  *Don't
be define by what you didn't know or didn't do.* *You're deciding
your life right now.* 


<2013-07-24 Wed 14:05>
